name = "worker-typescript-template"
type = "javascript"
zone_id = ""
account_id = "144a45303d4243377f4b9da2334deaaa"
route = "https://worker-typescript-template.fahad10.workers.dev"
workers_dev = true
compatibility_date = "2022-05-26"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
