name = "whydonate_backend"
main = "./dist/worker.js"
type = "javascript"
# zone_id = "https://backend.whydonate.workers.dev/"
account_id = "a14a8123f4abd24df8e9df9512399197"
# route = "https://backend.whydonate.workers.dev/"
workers_dev = true
compatibility_date = "2022-04-04"
# webpack_config = "webpack.config.js"
[build]
command = "yarn run build"
[build.upload]
format = "service-worker"